package com.owain.chinmanager.magicnumbers;

import net.runelite.api.widgets.WidgetID;

public enum MagicNumberWidgets
{
	LOGIN_SCREEN_PLAY_NOW(WidgetID.LOGIN_CLICK_TO_PLAY_GROUP_ID, MagicNumberWidget.LOGIN_SCREEN_PLAY_NOW),
	LOGIN_SCREEN_PLAY_NOW_TEXT(WidgetID.LOGIN_CLICK_TO_PLAY_GROUP_ID, MagicNumberWidget.LOGIN_SCREEN_PLAY_NOW_TEXT),


	LOG_OUT_BUTTON(MagicNumberWidget.LOG_OUT_CONTAINER, MagicNumberWidget.LOG_OUT_BUTTON),
	LOG_OUT_DOOR(MagicNumberWidget.WORLD_HOP_CONTAINER, MagicNumberWidget.LOG_OUT_DOOR),


	CONTACT_NPC_CONTAINER(MagicNumberWidget.CONTACT_NPC_CONTAINER, MagicNumberWidget.CONTACT_NPC_MAIN),
	CONTACT_NPC_AMY(MagicNumberWidget.CONTACT_NPC_CONTAINER, MagicNumberWidget.CONTACT_NPC_AMY),


	GROUPING_TAB(MagicNumberWidget.GROUPING_CONTAINER, MagicNumberWidget.GROUPING_TAB),


	TELEPORT_LOG(MagicNumberWidget.TELEPORT_LOG, MagicNumberWidget.TELEPORT_LOG_MAIN),
	NEXUS_TELEPORTS(MagicNumberWidget.NEXUS_CONTAINER, MagicNumberWidget.NEXUS_TELEPORTS),
	JEWELLERY_BOX(MagicNumberWidget.JEWELLERY_BOX_CONTAINER, MagicNumberWidget.JEWELLERY_BOX_MAIN),


	LOADING_HOME_MAIN(MagicNumberWidget.LOADING_HOME_CONTAINER, MagicNumberWidget.LOADING_HOME_MAIN),


	NPC_CONTINUE(WidgetID.DIALOG_NPC_GROUP_ID, MagicNumberWidget.CONTINUE),
	PLAYER_CONTINUE(WidgetID.DIALOG_PLAYER_GROUP_ID, MagicNumberWidget.CONTINUE),


	BANK_DEPOSIT_BOX_CONTAINER_MAIN(MagicNumberWidget.BANK_DEPOSIT_BOX_CONTAINER, MagicNumberWidget.BANK_DEPOSIT_BOX_CONTAINER_MAIN),
	BANK_DEPOSIT_BOX_WITHDRAW_ONE(MagicNumberWidget.BANK_DEPOSIT_BOX_CONTAINER, MagicNumberWidget.BANK_DEPOSIT_BOX_WITHDRAW_ONE),
	BANK_DEPOSIT_BOX_WITHDRAW_X(MagicNumberWidget.BANK_DEPOSIT_BOX_CONTAINER, MagicNumberWidget.BANK_DEPOSIT_BOX_WITHDRAW_X),
	BANK_DEPOSIT_BOX_WITHDRAW_ALL(MagicNumberWidget.BANK_DEPOSIT_BOX_CONTAINER, MagicNumberWidget.BANK_DEPOSIT_BOX_WITHDRAW_ALL),


	BANK_CONTAINER_CONTAINER(MagicNumberWidget.BANK_CONTAINER, MagicNumberWidget.BANK_CONTAINER_MAIN),
	BANK_WITHDRAW_ONE(MagicNumberWidget.BANK_CONTAINER, MagicNumberWidget.BANK_WITHDRAW_ONE),
	BANK_WITHDRAW_X(MagicNumberWidget.BANK_CONTAINER, MagicNumberWidget.BANK_WITHDRAW_X),
	BANK_WITHDRAW_ALL(MagicNumberWidget.BANK_CONTAINER, MagicNumberWidget.BANK_WITHDRAW_ALL),
	BANK_INVENTORY_OPTIONS(MagicNumberWidget.BANK_CONTAINER, MagicNumberWidget.BANK_INVENTORY_OPTIONS),
	BANK_EQUIPMENT_HEAD(MagicNumberWidget.BANK_CONTAINER, MagicNumberWidget.BANK_EQUIPMENT_HEAD),
	BANK_EQUIPMENT_CAPE(MagicNumberWidget.BANK_CONTAINER, MagicNumberWidget.BANK_EQUIPMENT_CAPE),
	BANK_EQUIPMENT_AMULET(MagicNumberWidget.BANK_CONTAINER, MagicNumberWidget.BANK_EQUIPMENT_AMULET),
	BANK_EQUIPMENT_WEAPON(MagicNumberWidget.BANK_CONTAINER, MagicNumberWidget.BANK_EQUIPMENT_WEAPON),
	BANK_EQUIPMENT_BODY(MagicNumberWidget.BANK_CONTAINER, MagicNumberWidget.BANK_EQUIPMENT_BODY),
	BANK_EQUIPMENT_SHIELD(MagicNumberWidget.BANK_CONTAINER, MagicNumberWidget.BANK_EQUIPMENT_SHIELD),
	BANK_EQUIPMENT_LEGS(MagicNumberWidget.BANK_CONTAINER, MagicNumberWidget.BANK_EQUIPMENT_LEGS),
	BANK_EQUIPMENT_GLOVES(MagicNumberWidget.BANK_CONTAINER, MagicNumberWidget.BANK_EQUIPMENT_GLOVES),
	BANK_EQUIPMENT_BOOTS(MagicNumberWidget.BANK_CONTAINER, MagicNumberWidget.BANK_EQUIPMENT_BOOTS),
	BANK_EQUIPMENT_RING(MagicNumberWidget.BANK_CONTAINER, MagicNumberWidget.BANK_EQUIPMENT_RING),
	BANK_EQUIPMENT_AMMO(MagicNumberWidget.BANK_CONTAINER, MagicNumberWidget.BANK_EQUIPMENT_AMMO),


	LEPRECHAUN_STORE_CONTAINER(MagicNumberWidget.LEPRECHAUN_STORE, MagicNumberWidget.LEPRECHAUN_STORE_MAIN),
	LEPRECHAUN_STORE_WITHDRAW_ONE(MagicNumberWidget.LEPRECHAUN_STORE, MagicNumberWidget.LEPRECHAUN_STORE_WITHDRAW_ONE),
	LEPRECHAUN_STORE_PLANT_CURE(MagicNumberWidget.LEPRECHAUN_STORE, MagicNumberWidget.LEPRECHAUN_STORE_PLANT_CURE),
	LEPRECHAUN_STORE_BOTTOMLESS_BUCKET(MagicNumberWidget.LEPRECHAUN_STORE, MagicNumberWidget.LEPRECHAUN_STORE_BOTTOMLESS_BUCKET),
	LEPRECHAUN_STORE_BUCKETS(MagicNumberWidget.LEPRECHAUN_STORE, MagicNumberWidget.LEPRECHAUN_STORE_BUCKETS),
	LEPRECHAUN_STORE_COMPOST(MagicNumberWidget.LEPRECHAUN_STORE, MagicNumberWidget.LEPRECHAUN_STORE_COMPOST),
	LEPRECHAUN_STORE_SUPER_COMPOST(MagicNumberWidget.LEPRECHAUN_STORE, MagicNumberWidget.LEPRECHAUN_STORE_SUPER_COMPOST),
	LEPRECHAUN_STORE_ULTRA_COMPOST(MagicNumberWidget.LEPRECHAUN_STORE, MagicNumberWidget.LEPRECHAUN_STORE_ULTRA_COMPOST),

	LEPRECHAUN_STORE_INV_PLANT_CURE(MagicNumberWidget.LEPRECHAUN_STORE_INV, MagicNumberWidget.LEPRECHAUN_STORE_INV_PLANT_CURE),
	LEPRECHAUN_STORE_INV_BOTTOMLESS_BUCKET(MagicNumberWidget.LEPRECHAUN_STORE_INV, MagicNumberWidget.LEPRECHAUN_STORE_INV_BOTTOMLESS_BUCKET),
	LEPRECHAUN_STORE_INV_BUCKETS(MagicNumberWidget.LEPRECHAUN_STORE_INV, MagicNumberWidget.LEPRECHAUN_STORE_INV_BUCKETS),
	LEPRECHAUN_STORE_INV_COMPOST(MagicNumberWidget.LEPRECHAUN_STORE_INV, MagicNumberWidget.LEPRECHAUN_STORE_INV_COMPOST),
	LEPRECHAUN_STORE_INV_SUPER_COMPOST(MagicNumberWidget.LEPRECHAUN_STORE_INV, MagicNumberWidget.LEPRECHAUN_STORE_INV_SUPER_COMPOST),
	LEPRECHAUN_STORE_INV_ULTRA_COMPOST(MagicNumberWidget.LEPRECHAUN_STORE_INV, MagicNumberWidget.LEPRECHAUN_STORE_INV_ULTRA_COMPOST),

	REWARD_STORE_CONTAINER(MagicNumberWidget.REWARD_STORE, MagicNumberWidget.REWARD_STORE_MAIN),

	ALCHEMIST_POINTS(MagicNumberWidget.ALCHEMIST_CONTAINER, MagicNumberWidget.MTA_POINTS),
	ENCHANTMENT_POINTS(MagicNumberWidget.ENCHANTMENT_CONTAINER, MagicNumberWidget.MTA_POINTS),
	GRAVEYARD_POINTS(MagicNumberWidget.GRAVEYARD_CONTAINER, MagicNumberWidget.MTA_POINTS),
	TELEKINETIC_POINTS(MagicNumberWidget.TELEKINETIC_CONTAINER, MagicNumberWidget.MTA_POINTS),

	MAHOGANY_HOMES_BUILD(MagicNumberWidget.MAHOGANY_HOMES_BUILD_CONTAINER, MagicNumberWidget.MAHOGANY_HOMES_BUILD_MAIN),

	;

	private final int groupId;
	private final int childId;

	MagicNumberWidgets(int groupId, int childId)
	{
		this.groupId = groupId;
		this.childId = childId;
	}

	public int getGroupId()
	{
		return groupId;
	}
	public int getChildId()
	{
		return childId;
	}
}

